const $=s=>document.querySelector(s);
function fitArtboard(){document.body.style.width='1440px';document.body.style.zoom=Math.min(1,window.innerWidth/1440);}
window.addEventListener('resize',fitArtboard);fitArtboard();
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.view;$('#reading').hidden=v!=='reading';$('#knowledge').hidden=v!=='knowledge';document.querySelectorAll('.review button').forEach(t=>t.classList.toggle('active',t.dataset.view===v));});
const answers=[['模型如何调用工具','模型输出的不是执行结果，而是调用工具的请求','模型输出工具名称和参数，由应用程序执行，再把结果交回模型。','一次调用可以分成三步：模型提出请求，应用程序运行工具，模型读取返回结果。例如模型请求查询北京天气，应用程序访问天气服务，模型再根据返回的温度回答。'],['谁在真正执行工具','应用程序执行这个请求','模型负责提出请求，真正执行工具的是模型外面的应用程序。','可以把模型想成点菜的人：它说「查一下北京的天气」，但不会亲自连接天气服务。应用程序收到工具名和参数，运行对应代码，再把查询结果交回来。是否允许执行、如何处理失败，都由应用程序控制。'],['结果如何交回模型','再把结果交回模型','应用程序把工具执行结果作为新的上下文交给模型。','例如，天气工具返回北京当前的温度。应用程序把这份结果和对应的调用关联起来，再让模型继续回答。模型读到的是返回的数据，不是亲自观察到了天气。']];
document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-node]').forEach(n=>n.classList.remove('selected'));b.classList.add('selected');const a=answers[+b.dataset.node];$('#answer-title').textContent=a[0];$('#selected-quote').textContent='「'+a[1]+'」';$('#answer-content').innerHTML='<small>原文说的是</small><p>'+a[2]+'</p><small>补充解释</small><p>'+a[3]+'</p>';$('#step').textContent=b.dataset.node==='0'?'根节点':'追问 0'+b.dataset.node;$('#followup').hidden=true;});
$('#binding').onclick=()=>$('#candidates').hidden=!$('#candidates').hidden;
document.querySelectorAll('.candidate').forEach(b=>b.onclick=()=>{$('#binding').textContent='已挂靠：'+b.textContent.replace(' · ','（')+'）';$('#candidates').hidden=true;});
$('#answer-content').onmouseup=()=>{const s=getSelection().toString().trim();if(s){$('#followup').hidden=false;$('#selection-text').textContent='继续探索：「'+s+'」';}};
$('#followup').onsubmit=e=>{e.preventDefault();$('#selection-text').textContent='设计演示：已选中高亮；实际回答将在接入模型后生成。';};
$('#expand').onclick=()=>{$('#leaves').hidden=!$('#leaves').hidden;};
document.querySelectorAll('[data-concept]').forEach(b=>b.onclick=()=>{$('#concept').textContent=b.dataset.concept;const lit=b.dataset.concept==='工具调用';$('.record').hidden=!lit;$('#empty').hidden=lit;$('#record-count').textContent=lit?'1':'0';document.querySelectorAll('.current').forEach(n=>n.classList.remove('current'));b.classList.add('current');});
let scale=1,x=0,y=0;function transform(){$('#map').style.transform=`translate(${x}px,${y}px) scale(${scale})`;$('#scale').textContent=Math.round(scale*100)+'%';}$('#plus').onclick=()=>{scale=Math.min(1.5,scale+.1);transform();};$('#minus').onclick=()=>{scale=Math.max(.5,scale-.1);transform();};$('#reset').onclick=()=>{scale=1;x=y=0;transform();};let drag;$('.canvas').onpointerdown=e=>{if(e.target.closest('button'))return;drag=[e.clientX-x,e.clientY-y];$('.canvas').setPointerCapture(e.pointerId);};$('.canvas').onpointermove=e=>{if(drag){x=e.clientX-drag[0];y=e.clientY-drag[1];transform();}};$('.canvas').onpointerup=()=>drag=null;
