import { describe, it, expect, beforeEach } from 'vitest';
import {
  classifyArticle,
  generateRoot,
  generateFollowup,
  setMockScenario,
} from '../../server/agent/index.js';
import {
  agentArticleFixture,
  psychologyArticleFixture,
  distributedSystemsArticleFixture,
  unknownArticleFixture,
  sampleTreeContextFixture,
} from '@zhihu-explore/fixtures';
import type { SkeletonNode } from '@zhihu-explore/contracts';

const mockSkeleton: SkeletonNode[] = [
  {
    id: 'agent-app-dev/root',
    parent_id: null,
    title: 'Agent 应用开发',
    aliases: [],
    definition: '核心定义',
  },
  {
    id: 'agent-app-dev/tool-calling',
    parent_id: 'agent-app-dev/root',
    title: '工具使用与调用',
    aliases: [],
    definition: '工具调用定义',
  },
  {
    id: 'agent-app-dev/memory-systems',
    parent_id: 'agent-app-dev/root',
    title: '记忆系统',
    aliases: [],
    definition: '记忆系统定义',
  },
];

describe('Agent Contract Tests (Mock Mode)', () => {
  beforeEach(() => {
    setMockScenario('default');
  });

  describe('classifyArticle', () => {
    it('classifies agent article accurately', async () => {
      const res = await classifyArticle({
        title: agentArticleFixture.title,
        tags: agentArticleFixture.tags,
        lead: agentArticleFixture.content_text.slice(0, 100),
      });
      expect(res.slug).toBe('agent-app-dev');
    });

    it('classifies cognitive psychology article', async () => {
      const res = await classifyArticle({
        title: psychologyArticleFixture.title,
        tags: psychologyArticleFixture.tags,
        lead: psychologyArticleFixture.content_text.slice(0, 100),
      });
      expect(res.slug).toBe('cognitive-psychology');
    });

    it('classifies distributed systems article', async () => {
      const res = await classifyArticle({
        title: distributedSystemsArticleFixture.title,
        tags: distributedSystemsArticleFixture.tags,
        lead: distributedSystemsArticleFixture.content_text.slice(0, 100),
      });
      expect(res.slug).toBe('distributed-systems');
    });

    it('returns null slug for unmatched domain', async () => {
      const res = await classifyArticle({
        title: unknownArticleFixture.title,
        tags: unknownArticleFixture.tags,
        lead: unknownArticleFixture.content_text.slice(0, 100),
      });
      expect(res.slug).toBeNull();
    });
  });

  describe('generateRoot contract constraints', () => {
    it('never includes answer_original field in agent output', async () => {
      const res = await generateRoot({
        article: agentArticleFixture,
        tree: sampleTreeContextFixture,
        highlight: '工具调用（Tool Calling / Function Calling）',
        question: '为什么需要工具调用？',
        historySummary: '',
        disciplineSkeleton: mockSkeleton,
      });

      expect(res.title).toBeDefined();
      expect(res.extra).toBeDefined();
      expect(res.sources).toBeDefined();
      expect(res.candidates).toBeDefined();
      expect(res.candidates.length).toBeLessThanOrEqual(3);
      // Crucial contract requirement: no original text field generated by model
      expect('answer_original' in res).toBe(false);
      expect('original' in res).toBe(false);
    });

    it('supports exact_match scenario with valid candidates', async () => {
      setMockScenario('exact_match');
      const res = await generateRoot({
        article: agentArticleFixture,
        tree: sampleTreeContextFixture,
        highlight: '工具调用',
        question: '',
        historySummary: '',
        disciplineSkeleton: mockSkeleton,
      });

      expect(res.candidates.length).toBe(1);
      expect(res.candidates[0]!.degree).toBe('exact');
      expect(res.candidates[0]!.node_id).toBe('agent-app-dev/tool-calling');
    });

    it('supports broader_then_exact scenario', async () => {
      setMockScenario('broader_then_exact');
      const res = await generateRoot({
        article: agentArticleFixture,
        tree: sampleTreeContextFixture,
        highlight: '工具调用',
        question: '',
        historySummary: '',
        disciplineSkeleton: mockSkeleton,
      });

      expect(res.candidates.length).toBe(2);
      expect(res.candidates[0]!.degree).toBe('broader');
      expect(res.candidates[1]!.degree).toBe('exact');
    });

    it('supports zero_candidates scenario', async () => {
      setMockScenario('zero_candidates');
      const res = await generateRoot({
        article: agentArticleFixture,
        tree: sampleTreeContextFixture,
        highlight: '工具调用',
        question: '',
        historySummary: '',
        disciplineSkeleton: mockSkeleton,
      });

      expect(res.candidates).toEqual([]);
    });

    it('produces deterministic output on repeated invocations', async () => {
      const req = {
        article: agentArticleFixture,
        tree: sampleTreeContextFixture,
        highlight: '工具调用',
        question: '核心机制',
        historySummary: '',
        disciplineSkeleton: mockSkeleton,
      };

      const res1 = await generateRoot(req);
      const res2 = await generateRoot(req);
      expect(res1).toEqual(res2);
    });
  });

  describe('generateFollowup contract constraints', () => {
    it('does NOT contain candidates field in followup output', async () => {
      const res = await generateFollowup({
        article: agentArticleFixture,
        tree: sampleTreeContextFixture,
        highlight: '结构化 JSON 参数',
        question: '如何防错？',
      });

      expect(res.title).toBeDefined();
      expect(res.extra).toBeDefined();
      expect(res.sources).toBeDefined();
      // Crucial contract requirement: followup output has no candidates
      expect('candidates' in res).toBe(false);
      expect('answer_original' in res).toBe(false);
    });
  });

  describe('failure and error handling scenarios', () => {
    it('propagates failure when simulated', async () => {
      setMockScenario('failure');
      await expect(
        classifyArticle({
          title: 'test',
          tags: [],
          lead: 'test',
        }),
      ).rejects.toThrow('Mock Agent classify failure simulated');

      await expect(
        generateRoot({
          article: agentArticleFixture,
          tree: sampleTreeContextFixture,
          highlight: 'test',
          question: '',
          historySummary: '',
          disciplineSkeleton: mockSkeleton,
        }),
      ).rejects.toThrow('Mock Agent generateRoot failure simulated');

      await expect(
        generateFollowup({
          article: agentArticleFixture,
          tree: sampleTreeContextFixture,
          highlight: 'test',
          question: '',
        }),
      ).rejects.toThrow('Mock Agent generateFollowup failure simulated');
    });
  });
});
